# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomTabBar-41' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Localize' , '~> 2.1.0'
  # Pods for CustomTabBar-41

end
